### ISSUE TITLE
Usability: Misleading error message when report file can not be created

### ISSUE THREAD

**Issue by arnemertz** [blackducksoftware/import_yocto_bm#6]
When I use the `--report` option with a path that I have no access to or where the directory does not exist, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/import_yocto_bm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/import_yocto_bm/main.py", line 56, in main
    process.proc_yocto_project(config.args.manifest)
  File "/usr/local/lib/python3.9/dist-packages/import_yocto_bm/process.py", line 275, in proc_yocto_project
    utils.check_recipes(config.args.kb_recipe_dir)
  File "/usr/local/lib/python3.9/dist-packages/import_yocto_bm/utils.py", line 438, in check_recipes
    repfile.close()
UnboundLocalError: local variable 'repfile' referenced before assignment
```

**Comment by matthewb66** [comment]
The logic should cover this case - but recommended that run the utility in a folder with write permission anyway (or specify a path where you have write permission).
I'll make a change in forthcoming v2.2
